// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOKSELa8l4HMimDYtaeHY4HOyvqnLVh7A',
    appId: '1:527767607365:web:443c125e708a00e5966b2c',
    messagingSenderId: '527767607365',
    projectId: 'right-aid',
    authDomain: 'right-aid.firebaseapp.com',
    storageBucket: 'right-aid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb0llXbEbQhnyr8xr0Ltce5DyCwjyu6mE',
    appId: '1:527767607365:android:469706432b85dbac966b2c',
    messagingSenderId: '527767607365',
    projectId: 'right-aid',
    storageBucket: 'right-aid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCllsHix0bYeuYm5ylyeuqh8rlYGdqiUhM',
    appId: '1:527767607365:ios:5974187740a29b86966b2c',
    messagingSenderId: '527767607365',
    projectId: 'right-aid',
    storageBucket: 'right-aid.appspot.com',
    iosBundleId: 'com.example.rightAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCllsHix0bYeuYm5ylyeuqh8rlYGdqiUhM',
    appId: '1:527767607365:ios:aa4125ce37df80db966b2c',
    messagingSenderId: '527767607365',
    projectId: 'right-aid',
    storageBucket: 'right-aid.appspot.com',
    iosBundleId: 'com.example.rightAid.RunnerTests',
  );
}
